In [14]:
import spectral as spy
import spectral.io.envi as envi

meta_cube = envi.open(r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_1\spectral_image_processed_image.hdr", r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_1\spectral_image_processed_image.bin")
cube = meta_cube.load()

In [10]:
cube

ImageArray([[[31. 26. 14. ...  7.  7.  7.]
             [10. 33. 19. ...  5.  4.  4.]
             [67. 42. 15. ...  2.  1.  0.]
             ...
             [12.  9.  8. ...  1.  1.  1.]
             [12.  6.  4. ...  1.  1.  1.]
             [ 7.  7. 14. ...  0.  0.  0.]]

            [[34. 56. 62. ...  4.  4.  4.]
             [ 6. 18. 23. ...  3.  3.  4.]
             [28. 17. 26. ...  1.  1.  1.]
             ...
             [ 2. 10. 10. ...  0.  0.  0.]
             [12.  2.  2. ...  2.  2.  2.]
             [16.  7.  0. ...  0.  0.  0.]]

            [[17.  2. 20. ...  2.  2.  2.]
             [23.  4. 42. ...  5.  5.  5.]
             [28. 27. 25. ...  1.  1.  1.]
             ...
             [11. 10. 18. ...  2.  2.  2.]
             [13. 21. 21. ...  4.  4.  4.]
             [19. 13. 13. ...  0.  0.  0.]]

            ...

            [[11. 18. 38. ...  5.  5.  5.]
             [27.  4. 10. ...  6.  5.  5.]
             [33. 37. 23. ...  2.  2.  3.]
             ...
      

In [12]:
rgb_bands = (29, 19, 9)  # Example of selecting three bands to map to R, G, B

spy.save_rgb('output_rgb_image.png', cube, rgb_bands)

In [15]:
import numpy as np
import spectral.io.envi as envi

# Load the two cubes
cube1 = envi.open(r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_1\spectral_image_processed_image.hdr", r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_1\spectral_image_processed_image.bin").load()
cube2 = envi.open(r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_2\spectral_image_processed_image.hdr", r"C:\Users\meloy\Desktop\Orbeli\DemoWithTigran\DemoForTIgran_09-18_600_2\spectral_image_processed_image.bin").load()

# Ensure both cubes have the same shape before addition
assert cube1.shape == cube2.shape, "Cubes must have the same dimensions."

# Add the cubes
combined_cube = cube1 + cube2

rgb_bands = (29, 19, 9)  

spy.save_rgb('combined.png', combined_cube, rgb_bands)

C:\Users\meloy\AppData\Local\Temp\ipykernel_8624\2236225852.py:12: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  combined_cube = cube1 + cube2
